Repository AlexsLemonade/OpenPBTA-analysis, pull requests merged in 2019-12, with the labels that each got.

#308 CI: Representative reported_gender in stranded subset files
  .circleci/config.yml
  analyses/create-subset-files/01-get_biospecimen_identifiers.R
  analyses/create-subset-files/biospecimen_ids_for_subset.RDS
Labels: ci

#336 Template markdown file for tracking data information/descriptions
  doc/data-description.md
Labels: data, discussion, documentation

#345 Add "modules at a glance" table
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  analyses/README.md
Labels: documentation

#347 Release V12 data
  doc/data-files-description.md
  doc/data-formats.md
  doc/release-notes.md
  download-data.sh
Labels: ready for review

#356 CI files: Account for v12 release changes
  analyses/create-subset-files/01-get_biospecimen_identifiers.R
  analyses/create-subset-files/02-subset_files.R
  analyses/create-subset-files/biospecimen_ids_for_subset.RDS
  analyses/create-subset-files/create_subset_files.sh
Labels: ci
