Repository AlexsLemonade/OpenPBTA-analysis, pull requests merged in 2021-05, with the labels that each got.

#1038 V19 ci files
  .circleci/config.yml
  analyses/create-subset-files/biospecimen_ids_for_subset.RDS
  analyses/create-subset-files/create_subset_files.sh
  figures/mapping-histology-labels.Rmd
  figures/mapping-histology-labels.nb.html
  figures/palettes/histology_label_color_table.tsv
Labels: review before release, v19-release

#1033 Update MAF fields for v19 SNV consensus
  .circleci/config.yml
  analyses/snv-callers/compare_snv_callers_plots-tcga.nb.html
  analyses/snv-callers/compare_snv_callers_plots.nb.html
  analyses/snv-callers/plots/pbta-caller-comparison/pbta-frac_base_change_plot.png
  analyses/snv-callers/plots/pbta-caller-comparison/pbta-upset-plot-not-transcipts-only.png
  analyses/snv-callers/plots/pbta-caller-comparison/pbta-upset-plot-transcipts-only.png
  analyses/snv-callers/plots/pbta-caller-comparison/pbta-upset-plot.png
  analyses/snv-callers/plots/pbta-caller-comparison/pbta-vaf_cor_matrix.png
  analyses/snv-callers/plots/pbta-caller-comparison/pbta-vaf_distribution_plot.png
  analyses/snv-callers/plots/pbta-caller-comparison/pbta-variant_classification_plot.png
  analyses/snv-callers/plots/tcga-caller-comparison/tcga-frac-base-change-plot.png
  analyses/snv-callers/plots/tcga-caller-comparison/tcga-upset-plot-not-transcipts-only.png
  analyses/snv-callers/plots/tcga-caller-comparison/tcga-upset-plot-transcipts-only.png
  analyses/snv-callers/plots/tcga-caller-comparison/tcga-upset-plot.png
  analyses/snv-callers/plots/tcga-caller-comparison/tcga-vaf-cor-matrix.png
  analyses/snv-callers/plots/tcga-caller-comparison/tcga-vaf-distribution-plot.png
  analyses/snv-callers/plots/tcga-caller-comparison/tcga-variant-classification-plot.png
  analyses/snv-callers/run_caller_consensus_analysis-pbta.sh
  analyses/snv-callers/scripts/01-setup_db.py
  analyses/snv-callers/scripts/03-calculate_tmb.R
Labels: review before release, snv

#1026 v19-release
  doc/release-notes.md
  download-data.sh
Labels: merge next

#1016 Recode adamantinomatous craniopharyngiomas per #994
  analyses/molecular-subtyping-pathology/pathology-subtyping-craniopharyngioma.Rmd
  analyses/molecular-subtyping-pathology/pathology-subtyping-craniopharyngioma.nb.html
  analyses/molecular-subtyping-pathology/results/cranio_adam_subtypes.tsv
  analyses/molecular-subtyping-pathology/run-subtyping-aggregation.sh
Labels: molecular subtyping, work in progress

#1017 Add pathology subtyping of glialneuronal tumors
  analyses/molecular-subtyping-LGAT/lgat-subset/LGAT_fusion_subset.tsv
  analyses/molecular-subtyping-LGAT/results/lgat_subtyping.tsv
  analyses/molecular-subtyping-pathology/pathology-harmonized-diagnosis-glialneuronal-tumors.Rmd
  analyses/molecular-subtyping-pathology/pathology-harmonized-diagnosis-glialneuronal-tumors.nb.html
  analyses/molecular-subtyping-pathology/results/glialneuronal_tumor_subtypes.tsv
  analyses/molecular-subtyping-pathology/run-subtyping-aggregation.sh
Labels: molecular subtyping

#1066 Part1: Freec as default and neutral NA
  analyses/copy_number_consensus_call/README.md
  analyses/copy_number_consensus_call/results/pbta-cnv-consensus.seg.gz
  analyses/copy_number_consensus_call/run_consensus_call.sh
  analyses/copy_number_consensus_call/scripts/bed_to_segfile.R
Labels: merge next

#1055 Immunedeconv molsubtype
  analyses/immune-deconv/02-summary-plots.R
  analyses/immune-deconv/README.md
  analyses/immune-deconv/plots/heatmap_xCell_by_histology.pdf
  analyses/immune-deconv/plots/heatmap_xCell_by_molecular_subtype.pdf
  analyses/immune-deconv/results/deconv-output.RData
  analyses/immune-deconv/run-immune-deconv.sh
  analyses/immune-deconv/util/heatmap_by_histology.R
  analyses/immune-deconv/util/heatmap_by_molecular_subtype.R
Labels: merge next

#1051 Combine broad histology oncoprints into a single multi-panel plot
  analyses/oncoprint-landscape/plots/primary-plus_embryonal_goi_oncoprint.png
  analyses/oncoprint-landscape/plots/primary-plus_embryonal_oncoprint.png
  analyses/oncoprint-landscape/plots/primary-plus_ependymal_goi_oncoprint.png
  analyses/oncoprint-landscape/plots/primary-plus_ependymal_oncoprint.png
  analyses/oncoprint-landscape/plots/primary-plus_hgat_goi_oncoprint.png
  analyses/oncoprint-landscape/plots/primary-plus_hgat_oncoprint.png
  analyses/oncoprint-landscape/plots/primary-plus_lgat_goi_oncoprint.png
  analyses/oncoprint-landscape/plots/primary-plus_lgat_oncoprint.png
  analyses/oncoprint-landscape/plots/primary-plus_other_goi_oncoprint.png
  analyses/oncoprint-landscape/plots/primary-plus_other_oncoprint.png
  analyses/oncoprint-landscape/plots/primary_only_embryonal_goi_oncoprint.png
  analyses/oncoprint-landscape/plots/primary_only_embryonal_oncoprint.png
  analyses/oncoprint-landscape/plots/primary_only_ependymal_goi_oncoprint.png
  analyses/oncoprint-landscape/plots/primary_only_ependymal_oncoprint.png
  analyses/oncoprint-landscape/plots/primary_only_hgat_goi_oncoprint.png
  analyses/oncoprint-landscape/plots/primary_only_hgat_oncoprint.png
  analyses/oncoprint-landscape/plots/primary_only_lgat_goi_oncoprint.png
  analyses/oncoprint-landscape/plots/primary_only_lgat_oncoprint.png
  analyses/oncoprint-landscape/plots/primary_only_other_goi_oncoprint.png
  analyses/oncoprint-landscape/plots/primary_only_other_oncoprint.png
  figures/generate-figures.sh
  figures/mapping-histology-labels.nb.html
  figures/palettes/histology_label_color_table.tsv
  figures/pngs/fig3-oncoprint-landscape.png
  figures/pngs/primary-plus_oncoprint_landscape.png
  figures/pngs/primary_only_oncoprint_landscape.png
  figures/scripts/oncoprint-landscape.R
Labels: merge next

#1065 Add atypical choroid plexus papilloma to harmonized diagnosis
  analyses/molecular-subtyping-pathology/pathology-subtyping-choroid-plexus-papilloma.Rmd
  analyses/molecular-subtyping-pathology/pathology-subtyping-choroid-plexus-papilloma.nb.html
  analyses/molecular-subtyping-pathology/results/choroid_plexus_papilloma_subtypes.tsv
  analyses/molecular-subtyping-pathology/run-subtyping-aggregation.sh
Labels: merge next

#961 #819 Part2 : Scavenge back hotspots to add to consensus calls
  analyses/hotspots-detection/01-create-hotspot-maf.Rmd
  analyses/hotspots-detection/01-create-hotspot-maf.nb.html
  analyses/hotspots-detection/README.md
  analyses/hotspots-detection/input/maf_coltypes.RDS
  analyses/hotspots-detection/results/pbta-snv-scavenged-hotspots.maf.tsv.gz
  analyses/hotspots-detection/run_overlaps_hotspot.sh
  analyses/hotspots-detection/utils/filterMaf.R
  analyses/molecular-subtyping-pathology/results/choroid_plexus_papilloma_tumor_subtypes.tsv
Labels: merge next, ready for review

#1069 Rename module: sv-analysis -> chromothripsis
  .circleci/config.yml
  analyses/README.md
  analyses/chromothripsis/01-process-sv-file.R
  analyses/chromothripsis/02-shatterseek.R
  analyses/chromothripsis/README.md
  analyses/sv-analysis/README.md
  analyses/sv-analysis/result/PBTA_chromothripsis_newlink_region.csv
Labels: merge next

#1062 Update other-MAPK LGAT subtypes
  analyses/molecular-subtyping-LGAT/01-subset-files-for-LGAT.Rmd
  analyses/molecular-subtyping-LGAT/01-subset-files-for-LGAT.nb.html
  analyses/molecular-subtyping-LGAT/02-subset-fusion-files-LGAT.nb.html
  analyses/molecular-subtyping-LGAT/03-subset-cnv-files-LGAT.nb.html
  analyses/molecular-subtyping-LGAT/04-LGAT-compile-subtypes.nb.html
  analyses/molecular-subtyping-LGAT/README.md
  analyses/molecular-subtyping-LGAT/input/snvOI_list.json
  analyses/molecular-subtyping-LGAT/lgat-subset/LGAT_snv_subset.tsv
  analyses/molecular-subtyping-LGAT/results/lgat_subtyping.tsv
Labels: merge next

#1070 Remove irrelevant file that snuck in with #961
  analyses/molecular-subtyping-pathology/results/choroid_plexus_papilloma_tumor_subtypes.tsv
Labels: merge next

#1046 Update oncoprints to use histology-specific goi lists
  analyses/oncoprint-landscape/00-prepare-goi-lists.R
  analyses/oncoprint-landscape/01-map-to-sample_id.R
  analyses/oncoprint-landscape/02-plot-oncoprint.R
  analyses/oncoprint-landscape/data/embryonal-tumor_goi_list.tsv
  analyses/oncoprint-landscape/data/ependymal-tumor_goi_list.tsv
  analyses/oncoprint-landscape/data/hgat_goi_list.tsv
  analyses/oncoprint-landscape/data/lgat_goi_list.tsv
  analyses/oncoprint-landscape/data/oncoprint-goi-lists-OpenPBTA.csv
  analyses/oncoprint-landscape/data/other_goi_list.tsv
  analyses/oncoprint-landscape/plots/primary-plus_diffuse-astrocytic-and-oligodendroglial-tumor_goi_oncoprint.png
  analyses/oncoprint-landscape/plots/primary-plus_diffuse-astrocytic-and-oligodendroglial-tumor_oncoprint.png
  analyses/oncoprint-landscape/plots/primary-plus_embryonal-tumor_goi_oncoprint.png
  analyses/oncoprint-landscape/plots/primary-plus_embryonal-tumor_oncoprint.png
  analyses/oncoprint-landscape/plots/primary-plus_embryonal_goi_oncoprint.png
  analyses/oncoprint-landscape/plots/primary-plus_embryonal_oncoprint.png
  analyses/oncoprint-landscape/plots/primary-plus_ependymal-tumor_goi_oncoprint.png
  analyses/oncoprint-landscape/plots/primary-plus_ependymal-tumor_oncoprint.png
  analyses/oncoprint-landscape/plots/primary-plus_ependymal_goi_oncoprint.png
  analyses/oncoprint-landscape/plots/primary-plus_ependymal_oncoprint.png
  analyses/oncoprint-landscape/plots/primary-plus_hgat_goi_oncoprint.png
  analyses/oncoprint-landscape/plots/primary-plus_hgat_oncoprint.png
  analyses/oncoprint-landscape/plots/primary-plus_lgat_goi_oncoprint.png
  analyses/oncoprint-landscape/plots/primary-plus_lgat_oncoprint.png
  analyses/oncoprint-landscape/plots/primary-plus_low-grade-astrocytic-tumor_goi_oncoprint.png
  analyses/oncoprint-landscape/plots/primary-plus_low-grade-astrocytic-tumor_oncoprint.png
  analyses/oncoprint-landscape/plots/primary-plus_other-cns_goi_oncoprint.png
  analyses/oncoprint-landscape/plots/primary-plus_other-cns_oncoprint.png
  analyses/oncoprint-landscape/plots/primary-plus_other_goi_oncoprint.png
  analyses/oncoprint-landscape/plots/primary-plus_other_oncoprint.png
  analyses/oncoprint-landscape/plots/primary_only_diffuse-astrocytic-and-oligodendroglial-tumor_goi_oncoprint.png
  analyses/oncoprint-landscape/plots/primary_only_diffuse-astrocytic-and-oligodendroglial-tumor_oncoprint.png
  analyses/oncoprint-landscape/plots/primary_only_embryonal-tumor_goi_oncoprint.png
  analyses/oncoprint-landscape/plots/primary_only_embryonal-tumor_oncoprint.png
  analyses/oncoprint-landscape/plots/primary_only_embryonal_goi_oncoprint.png
  analyses/oncoprint-landscape/plots/primary_only_embryonal_oncoprint.png
  analyses/oncoprint-landscape/plots/primary_only_ependymal-tumor_goi_oncoprint.png
  analyses/oncoprint-landscape/plots/primary_only_ependymal-tumor_oncoprint.png
  analyses/oncoprint-landscape/plots/primary_only_ependymal_goi_oncoprint.png
  analyses/oncoprint-landscape/plots/primary_only_ependymal_oncoprint.png
  analyses/oncoprint-landscape/plots/primary_only_hgat_goi_oncoprint.png
  analyses/oncoprint-landscape/plots/primary_only_hgat_oncoprint.png
  analyses/oncoprint-landscape/plots/primary_only_lgat_goi_oncoprint.png
  analyses/oncoprint-landscape/plots/primary_only_lgat_oncoprint.png
  analyses/oncoprint-landscape/plots/primary_only_low-grade-astrocytic-tumor_goi_oncoprint.png
  analyses/oncoprint-landscape/plots/primary_only_low-grade-astrocytic-tumor_oncoprint.png
  analyses/oncoprint-landscape/plots/primary_only_other-cns_goi_oncoprint.png
  analyses/oncoprint-landscape/plots/primary_only_other-cns_oncoprint.png
  analyses/oncoprint-landscape/plots/primary_only_other_goi_oncoprint.png
  analyses/oncoprint-landscape/plots/primary_only_other_oncoprint.png
  analyses/oncoprint-landscape/run-oncoprint.sh
  analyses/oncoprint-landscape/util/oncoplot-functions.R
  figures/palettes/oncoprint_color_palette.tsv
Labels: merge next

#1060 Recode integrated-diagnosis for LGAT based on pathology-free-text-diagnosis
  analyses/molecular-subtyping-pathology/pathology_free_text-subtyping-lgat.Rmd
  analyses/molecular-subtyping-pathology/pathology_free_text-subtyping-lgat.nb.html
  analyses/molecular-subtyping-pathology/results/lgat-pathology-free-text-subtypes.tsv
  analyses/molecular-subtyping-pathology/run-subtyping-aggregation.sh
  analyses/molecular-subtyping-pathology/utils/recode_integrated_diagnosis.R
Labels: merge next
