Repository AlexsLemonade/OpenPBTA-analysis, pull requests merged in 2021-08, with the labels that each got.

#1138 rerun immune deconv with v20 data
  analyses/immune-deconv/plots/heatmap_xCell_by_histology.pdf
  analyses/immune-deconv/plots/heatmap_xCell_by_molecular_subtype.pdf
  analyses/immune-deconv/results/deconv-output.RData
Labels: ready for review, merge next

#1143 oncoprint update PR 1/n
  analyses/oncoprint-landscape/02-plot-oncoprint.R
  analyses/oncoprint-landscape/README.md
  analyses/oncoprint-landscape/data/embryonal-tumor_goi_list.tsv
  analyses/oncoprint-landscape/data/ependymal-tumor_goi_list.tsv
  analyses/oncoprint-landscape/data/hgat_goi_list.tsv
  analyses/oncoprint-landscape/data/oncoprint-goi-lists-OpenPBTA.csv
  analyses/oncoprint-landscape/data/other_goi_list.tsv
  analyses/oncoprint-landscape/plots/primary-plus_embryonal_goi_oncoprint.png
  analyses/oncoprint-landscape/plots/primary-plus_embryonal_oncoprint.png
  analyses/oncoprint-landscape/plots/primary-plus_ependymal_goi_oncoprint.png
  analyses/oncoprint-landscape/plots/primary-plus_ependymal_oncoprint.png
  analyses/oncoprint-landscape/plots/primary-plus_hgat_goi_oncoprint.png
  analyses/oncoprint-landscape/plots/primary-plus_hgat_oncoprint.png
  analyses/oncoprint-landscape/plots/primary-plus_lgat_goi_oncoprint.png
  analyses/oncoprint-landscape/plots/primary-plus_lgat_oncoprint.png
  analyses/oncoprint-landscape/plots/primary-plus_other_goi_oncoprint.png
  analyses/oncoprint-landscape/plots/primary-plus_other_oncoprint.png
  analyses/oncoprint-landscape/plots/primary_only_embryonal_goi_oncoprint.png
  analyses/oncoprint-landscape/plots/primary_only_embryonal_oncoprint.png
  analyses/oncoprint-landscape/plots/primary_only_ependymal_goi_oncoprint.png
  analyses/oncoprint-landscape/plots/primary_only_ependymal_oncoprint.png
  analyses/oncoprint-landscape/plots/primary_only_hgat_goi_oncoprint.png
  analyses/oncoprint-landscape/plots/primary_only_hgat_oncoprint.png
  analyses/oncoprint-landscape/plots/primary_only_lgat_goi_oncoprint.png
  analyses/oncoprint-landscape/plots/primary_only_lgat_oncoprint.png
  analyses/oncoprint-landscape/plots/primary_only_other_goi_oncoprint.png
  analyses/oncoprint-landscape/plots/primary_only_other_oncoprint.png
  analyses/oncoprint-landscape/run-oncoprint.sh
Labels: ready for review

#1156 PBTA histologies v21: PR1 Include SEGA to molecular-subtyping-LGAT
  analyses/molecular-subtyping-LGAT/00-LGAT-select-pathology-dx.R
  analyses/molecular-subtyping-LGAT/01-subset-files-for-LGAT.nb.html
  analyses/molecular-subtyping-LGAT/03-subset-cnv-files-LGAT.nb.html
  analyses/molecular-subtyping-LGAT/04-LGAT-compile-subtypes.Rmd
  analyses/molecular-subtyping-LGAT/04-LGAT-compile-subtypes.nb.html
  analyses/molecular-subtyping-LGAT/README.md
  analyses/molecular-subtyping-LGAT/lgat-subset/LGAT_cnv_subset.tsv
  analyses/molecular-subtyping-LGAT/lgat-subset/LGAT_fusion_subset.tsv
  analyses/molecular-subtyping-LGAT/lgat-subset/LGAT_snv_subset.tsv
  analyses/molecular-subtyping-LGAT/lgat-subset/lgat_metadata.tsv
  analyses/molecular-subtyping-LGAT/lgat-subset/lgat_subtyping_path_dx_strings.json
  analyses/molecular-subtyping-LGAT/results/lgat_subtyping.tsv
Labels: merge next

#1157 Data release v21
  analyses/create-subset-files/create_subset_files.sh
  doc/data-formats.md
  doc/release-notes.md
  download-data.sh
Labels: merge next

#1163 update OpenPBTA bucket
  .circleci/config.yml
  download-data.sh
  scripts/download-ci-files.sh
Labels: merge next
