Repository AlexsLemonade/OpenPBTA-analysis, pull requests merged in 2021-01, with the labels that each got.

#863 PBTA Histologies: Update collapse-rnaseq to v18 (1 of N)
  analyses/collapse-rnaseq/02-analyze-drops.nb.html
  analyses/collapse-rnaseq/results/pbta-gene-expression-rsem-fpkm-collapsed_table.stranded.rds
  analyses/collapse-rnaseq/run-collapse-rnaseq.sh
Labels: review before release

#864 PBTA Histologies: Independent sample base (2 of N)
  .circleci/config.yml
  analyses/independent-samples/00-repeated-samples.Rmd
  analyses/independent-samples/00-repeated-samples.nb.html
  analyses/independent-samples/README.md
  analyses/independent-samples/results/independent-specimens.rnaseq.primary-plus-stranded.tsv
  analyses/independent-samples/results/independent-specimens.wgs.primary-plus.tsv
  analyses/independent-samples/results/independent-specimens.wgs.primary.tsv
  analyses/independent-samples/results/independent-specimens.wgswxs.primary-plus.tsv
  analyses/independent-samples/results/independent-specimens.wgswxs.primary.tsv
  analyses/independent-samples/run-independent-samples.sh
Labels: review before release

#866 PBTA Histologies: Fusion summary base (4 of N)
  analyses/fusion-summary/01-fusion-summary.nb.html
  analyses/fusion-summary/results/fusion_summary_embryonal_foi.tsv
  analyses/fusion-summary/results/fusion_summary_ependymoma_foi.tsv
  analyses/fusion-summary/results/fusion_summary_ewings_foi.tsv
  analyses/fusion-summary/results/fusion_summary_lgat_foi.tsv
Labels: don't merge, review before release

#870 PBTA Histologies: Integrated molecular subtyping to base histology (7 of N)
  .circleci/config.yml
  analyses/README.md
  analyses/molecular-subtyping-integrate/01-integrate-subtyping.Rmd
  analyses/molecular-subtyping-integrate/01-integrate-subtyping.nb.html
  analyses/molecular-subtyping-integrate/README.md
  analyses/molecular-subtyping-integrate/input/pathology_dx and pathology_free_text_diagnosis to broad_histology for subtyping module - rules_without_subtype_WIP.tsv
  analyses/molecular-subtyping-integrate/results/pbta-histologies.tsv
  analyses/molecular-subtyping-integrate/run-subtyping-integrate.sh
Labels: don't merge, review before release

#860 Ependymoma subtyping missing WGS only samples
  analyses/molecular-subtyping-EPN/01-make_notebook_RNAandDNA.py
  analyses/molecular-subtyping-EPN/02_ependymoma_generate_all_data.py
  analyses/molecular-subtyping-EPN/03-subgrouping_samples.html
  analyses/molecular-subtyping-EPN/03-subgrouping_samples.ipynb
  analyses/molecular-subtyping-EPN/results/EPN_all_data.tsv
  analyses/molecular-subtyping-EPN/results/EPN_all_data_withsubgroup.tsv
Labels: merge next

#842 #790 Part1: adding new SNV subtypes for LGAT
  analyses/molecular-subtyping-LGAT/01-subset-files-for-LGAT.R
  analyses/molecular-subtyping-LGAT/01-subset-files-for-LGAT.Rmd
  analyses/molecular-subtyping-LGAT/01-subset-files-for-LGAT.nb.html
  analyses/molecular-subtyping-LGAT/02-make-lgat-final-table.Rmd
  analyses/molecular-subtyping-LGAT/README.md
  analyses/molecular-subtyping-LGAT/input/snvOI_list.json
  analyses/molecular-subtyping-LGAT/lgat-subset/LGAT_snv_subset.tsv
  analyses/molecular-subtyping-LGAT/results/lgat_cleaned_all_table.tsv
  analyses/molecular-subtyping-LGAT/results/lgat_subtyping.tsv
  analyses/molecular-subtyping-LGAT/run_subtyping.sh
Labels: review after release

#857 add v18 release
  doc/release-notes.md
  download-data.sh
Labels: merge next, release

#892 v18 comparative RNA-seq fixes
  .circleci/config.yml
  analyses/comparative-RNASeq-analysis/01-correlation-matrix.py
  analyses/comparative-RNASeq-analysis/02-thresholds-and-outliers.py
  analyses/comparative-RNASeq-analysis/README.md
  analyses/comparative-RNASeq-analysis/run-comparative-RNAseq.sh
Labels: merge next

#856 Removing BRAF subtyping for HGG
  analyses/molecular-subtyping-HGG/01-HGG-molecular-subtyping-defining-lesions.Rmd
  analyses/molecular-subtyping-HGG/01-HGG-molecular-subtyping-defining-lesions.nb.html
  analyses/molecular-subtyping-HGG/07-HGG-molecular-subtyping-combine-table.Rmd
  analyses/molecular-subtyping-HGG/07-HGG-molecular-subtyping-combine-table.nb.html
  analyses/molecular-subtyping-HGG/09-HGG-with-braf-clustering.Rmd
  analyses/molecular-subtyping-HGG/09-HGG-with-braf-clustering.nb.html
  analyses/molecular-subtyping-HGG/README.md
  analyses/molecular-subtyping-HGG/plots/HGG_stranded.pdf
  analyses/molecular-subtyping-HGG/plots/HGG_stranded.png
  analyses/molecular-subtyping-HGG/results/HGG_molecular_subtype.tsv
  analyses/molecular-subtyping-HGG/run-molecular-subtyping-HGG.sh
Labels: merge next

#904 Using mapping histology groups for plotting -- Part 2 implemention (PR 1 of 4)
  analyses/chromosomal-instability/02a-plot-chr-instability-heatmaps.Rmd
  analyses/chromosomal-instability/02a-plot-chr-instability-heatmaps.nb.html
  analyses/chromosomal-instability/plots/cnv_breaks_heatmap.pdf
  analyses/chromosomal-instability/plots/intersection_breaks_heatmap.pdf
  analyses/chromosomal-instability/plots/sv_breaks_heatmap.pdf
  figures/README.md
  figures/generate-figures.sh
  figures/mapping-histology-labels.Rmd
  figures/mapping-histology-labels.nb.html
  figures/palettes/histology_label_color_table.tsv
  figures/scripts/color_palettes.R
Labels: merge next

#915 Replace `integrated_diagnosis` with `broad_histology` in interaction plots module
  .circleci/config.yml
  analyses/interaction-plots/01-create-interaction-plots.sh
  analyses/interaction-plots/plots/combined_top50.png
  analyses/interaction-plots/plots/cooccur_top50.ALL.png
  analyses/interaction-plots/plots/cooccur_top50.Craniopharyngioma.png
  analyses/interaction-plots/plots/cooccur_top50.DMG.png
  analyses/interaction-plots/plots/cooccur_top50.Diffuse-astrocytic-and-oligodendroglial-tumor.png
  analyses/interaction-plots/plots/cooccur_top50.Embryonal-tumor.png
  analyses/interaction-plots/plots/cooccur_top50.Ependymal-tumor.png
  analyses/interaction-plots/plots/cooccur_top50.Ganglioglioma.png
  analyses/interaction-plots/plots/cooccur_top50.HGAT.png
  analyses/interaction-plots/plots/cooccur_top50.LGAT.png
  analyses/interaction-plots/plots/cooccur_top50.Medulloblastoma.png
  analyses/interaction-plots/plots/cooccur_top50.Meningioma.png
  analyses/interaction-plots/plots/cooccur_top50.Neuronal-mixed-neuronal-glial-tumor.png
  analyses/interaction-plots/plots/cooccur_top50.Tumors-of-sellar-region.png
  analyses/interaction-plots/plots/gene_disease_top50.png
  analyses/interaction-plots/results/cooccur_top50.ALL.tsv
  analyses/interaction-plots/results/cooccur_top50.Craniopharyngioma.tsv
  analyses/interaction-plots/results/cooccur_top50.DMG.tsv
  analyses/interaction-plots/results/cooccur_top50.Diffuse-astrocytic-and-oligodendroglial-tumor.tsv
  analyses/interaction-plots/results/cooccur_top50.Embryonal-tumor.tsv
  analyses/interaction-plots/results/cooccur_top50.Ependymal-tumor.tsv
  analyses/interaction-plots/results/cooccur_top50.Ganglioglioma.tsv
  analyses/interaction-plots/results/cooccur_top50.HGAT.tsv
  analyses/interaction-plots/results/cooccur_top50.LGAT.tsv
  analyses/interaction-plots/results/cooccur_top50.Medulloblastoma.tsv
  analyses/interaction-plots/results/cooccur_top50.Meningioma.tsv
  analyses/interaction-plots/results/cooccur_top50.Neuronal-mixed-neuronal-glial-tumor.tsv
  analyses/interaction-plots/results/cooccur_top50.Tumors-of-sellar-region.tsv
  analyses/interaction-plots/results/gene_disease_top50.tsv
  analyses/interaction-plots/scripts/01-disease-specimen-lists.R
  analyses/interaction-plots/scripts/02-process_mutations.R
  analyses/interaction-plots/scripts/03-plot_interactions.R
Labels: merge next
