Repository AlexsLemonade/OpenPBTA-analysis, pull requests merged in 2022-06, with the labels that each got.

#1423 Docs changes related to #1399
  README.md
  analyses/README.md
  scripts/README.md
Labels: review before release

#1447 V22 sample distribution analysis rerun (14/N)
  analyses/sample-distribution-analysis/03-tumor-descriptor-and-assay-count.nb.html
  analyses/sample-distribution-analysis/04-ns-for-manuscript.nb.html
  analyses/sample-distribution-analysis/plots/distribution_across_cancer_types.pdf
  analyses/sample-distribution-analysis/plots/histology-pie.html
  analyses/sample-distribution-analysis/results/disease_expression.tsv
  analyses/sample-distribution-analysis/results/plots_df.tsv
  analyses/sample-distribution-analysis/results/primary_sites_counts.tsv
  analyses/sample-distribution-analysis/run-sample-distribution.sh
Labels: merge next

#1401 Update broad histology and cancer group palettes, etc. to reflect v22 release
  figures/mapping-histology-labels.Rmd
  figures/mapping-histology-labels.nb.html
  figures/palettes/broad_histology_cancer_group_palette.tsv
Labels: merge next

#1451 Docs updates - data files and analysis README
  analyses/README.md
  doc/data-files-description.md
Labels: ready to merge

#1456 V22 rerun sample distribution figure
  figures/pdfs/fig1/panels/tumor_descriptor_proportion_panel.pdf
  figures/pdfs/supp/sample-distribution/assay_pattern_legend.pdf
  figures/pdfs/supp/sample-distribution/assay_type_stacked_panel.pdf
  figures/scripts/fig1-sample-distribution.R
Labels: ready to merge

#1457 V22 chromothripsis figure update to use cancer group display
  analyses/chromothripsis/04-plot-chromothripsis-and-breakpoint-data.Rmd
  analyses/chromothripsis/plots/04-breakpoint-data/count_chromothripsis_cnv_and_sv_breaks_scatterplot.pdf
  analyses/chromothripsis/plots/04-breakpoint-data/count_chromothripsis_cnv_and_sv_breaks_scatterplot.png
  analyses/chromothripsis/plots/04-breakpoint-data/count_chromothripsis_cnv_breaks_stripchart.png
  analyses/chromothripsis/plots/04-breakpoint-data/count_chromothripsis_sv_breaks_stripchart.png
  figures/pdfs/fig3/panels/chromothripsis_prop_cancer_group.pdf
  figures/pdfs/fig3/panels/count_chromothripsis_cnv_and_sv_breaks_scatterplot.pdf
  figures/pdfs/supp/figs3/panels/supp_figS3-B.pdf
  figures/pdfs/supp/figs3/panels/supp_figS3-C.pdf
  figures/pdfs/supp/figs3/panels/supp_figS3-D.pdf
  figures/scripts/fig3-chromothripsis-barplot.R
  figures/scripts/supp-S3-panels-BCD.R
Labels: ready to merge
