Repository AlexsLemonade/OpenPBTA-analysis, pull requests merged in 2022-05, with the labels that each got.

#1387 update pathology free text for LGAT (1/2)
  .circleci/config.yml
  analyses/molecular-subtyping-pathology/02-compile-subtyping-pathology-free-text.nb.html
  analyses/molecular-subtyping-pathology/04-incorporate-pathology-feedback.nb.html
  analyses/molecular-subtyping-pathology/pathology_free_text-subtyping-lgat.Rmd
  analyses/molecular-subtyping-pathology/pathology_free_text-subtyping-lgat.nb.html
  analyses/molecular-subtyping-pathology/results/compiled_molecular_subtypes.tsv
  analyses/molecular-subtyping-pathology/results/compiled_molecular_subtypes_and_report_info.tsv
  analyses/molecular-subtyping-pathology/results/compiled_molecular_subtypes_with_clinical_feedback_and_report_info.tsv
  analyses/molecular-subtyping-pathology/results/compiled_molecular_subtypes_with_clinical_pathology_feedback_and_report_info.tsv
  analyses/molecular-subtyping-pathology/results/lgat-pathology-free-text-subtypes.tsv
Labels: merge next

#1400 Use ploidy for copy.num when running GISTIC
  analyses/run-gistic/README.md
  analyses/run-gistic/results/pbta-cnv-consensus-gistic-only.seg.gz
  analyses/run-gistic/run-gistic-module.sh
  analyses/run-gistic/scripts/prepare_seg_for_gistic.R
  analyses/run-gistic/scripts/run-gistic-openpbta.sh
Labels: merge next, blocking release, ready to merge

#1419 Update logic in modules where analysis files included in the data releases are generated
  analyses/focal-cn-file-preparation/README.md
  analyses/focal-cn-file-preparation/run-prepare-cn.sh
  analyses/fusion_filtering/README.md
  analyses/fusion_filtering/run_fusion_merged.sh
  analyses/independent-samples/README.md
  analyses/independent-samples/run-independent-samples.sh
Labels: merge next, blocking release, ready to merge

#1413 Make sure EWS subtyping uses data download
  analyses/molecular-subtyping-EWS/01-run-subtyping-ewings.Rmd
  analyses/molecular-subtyping-EWS/01-run-subtyping-ewings.nb.html
Labels: merge next, blocking release, ready to merge

#1415 Make sure non-ATRT/non-MB embryonal subtyping module uses data download
  .circleci/config.yml
  analyses/molecular-subtyping-embryonal/01-samples-to-subset.nb.html
  analyses/molecular-subtyping-embryonal/03-clean-c19mc-data.Rmd
  analyses/molecular-subtyping-embryonal/03-clean-c19mc-data.nb.html
  analyses/molecular-subtyping-embryonal/04-table-prep.Rmd
  analyses/molecular-subtyping-embryonal/04-table-prep.nb.html
  analyses/molecular-subtyping-embryonal/run-embryonal-subtyping.sh
Labels: merge next, blocking release, ready to merge

#1418 Make sure MB subtyping uses data download
  Dockerfile
  analyses/molecular-subtyping-MB/01-filter-and-batch-correction.R
  analyses/molecular-subtyping-MB/03-compare-classes.html
  analyses/molecular-subtyping-MB/04-no-RNA-samples.R
Labels: merge next, blocking release, ready to merge

#1420 Update snv-callers to be able to be run from places besides the root of repo
  analyses/snv-callers/README.md
  analyses/snv-callers/run_caller_consensus_analysis-pbta.sh
  analyses/snv-callers/run_caller_consensus_analysis-tcga.sh
  analyses/snv-callers/scripts/02-merge_callers.R
  analyses/snv-callers/scripts/03-calculate_tmb.R
  analyses/snv-callers/util/tmb_functions.R
  analyses/tp53_nf1_score/run_classifier.sh
  figures/scripts/supp-snv-callers-panels.R
Labels: review before release, blocking release

#1421 Add shell script to generate analysis files that are included in data releases
  scripts/generate-analysis-files-for-release.sh
Labels: merge next, blocking release

#1414 Make sure HGG subtyping uses data download
  analyses/molecular-subtyping-HGG/01-HGG-molecular-subtyping-defining-lesions.nb.html
  analyses/molecular-subtyping-HGG/02-HGG-molecular-subtyping-subset-files.R
  analyses/molecular-subtyping-HGG/03-HGG-molecular-subtyping-cnv.Rmd
  analyses/molecular-subtyping-HGG/03-HGG-molecular-subtyping-cnv.nb.html
  analyses/molecular-subtyping-HGG/04-HGG-molecular-subtyping-mutation.nb.html
  analyses/molecular-subtyping-HGG/05-HGG-molecular-subtyping-fusion.nb.html
  analyses/molecular-subtyping-HGG/06-HGG-molecular-subtyping-gene-expression.nb.html
  analyses/molecular-subtyping-HGG/07-HGG-molecular-subtyping-combine-table.Rmd
  analyses/molecular-subtyping-HGG/07-HGG-molecular-subtyping-combine-table.nb.html
  analyses/molecular-subtyping-HGG/08-1p19q-codeleted-oligodendrogliomas.nb.html
  analyses/molecular-subtyping-HGG/09-HGG-with-braf-clustering.nb.html
  analyses/molecular-subtyping-HGG/10-HGG-TP53-annotation.nb.html
  analyses/molecular-subtyping-HGG/README.md
  analyses/molecular-subtyping-HGG/hgg-subset/hgg_metadata.tsv
  analyses/molecular-subtyping-HGG/plots/HGG_stranded.pdf
  analyses/molecular-subtyping-HGG/plots/HGG_stranded.png
  analyses/molecular-subtyping-HGG/results/HGG_defining_lesions.tsv
  analyses/molecular-subtyping-HGG/results/HGG_molecular_subtype.tsv
  analyses/molecular-subtyping-HGG/run-molecular-subtyping-HGG.sh
Labels: merge next, blocking release

#1422 Revise shell script run for subtyping such that analysis file generation is removed
  analyses/chromosomal-instability/run_breakpoint_analysis.sh
  analyses/gene-set-enrichment-analysis/run-gsea.sh
  scripts/run-for-subtyping.sh
Labels: merge next, blocking release
