Repository AlexsLemonade/OpenPBTA-analysis, pull requests merged in 2023-01, with the labels that each got.

#1644 v23 create ci testing files
  analyses/create-subset-files/biospecimen_ids_for_subset.RDS
  analyses/create-subset-files/create_subset_files.sh
Labels: merge next

#1648 add v23 release notes (final N for release)
  doc/release-notes.md
  download-data.sh
Labels: merge next

#1642 Revision: Updates to sample distribution analysis module
  analyses/sample-distribution-analysis/03-tumor-descriptor-and-assay-count.nb.html
  analyses/sample-distribution-analysis/04-ns-for-manuscript.Rmd
  analyses/sample-distribution-analysis/04-ns-for-manuscript.nb.html
  analyses/sample-distribution-analysis/README.md
  analyses/sample-distribution-analysis/plots/distribution_across_cancer_types.pdf
  analyses/sample-distribution-analysis/plots/histology-pie.html
  analyses/sample-distribution-analysis/results/disease_expression.tsv
  analyses/sample-distribution-analysis/results/primary_sites_counts.tsv
  analyses/sample-distribution-analysis/run-sample-distribution.sh
Labels: ready for review

#1643 Revision: Update Table 1 to include Patient Ns
  tables/output_tables.Rmd
  tables/output_tables.nb.html
  tables/results/Table1-molecular-subtypes.tsv
  tables/results/TableS1-histologies.xlsx
  tables/results/TableS2-DNA-results-table.xlsx
  tables/results/TableS3-RNA-results-table.xlsx
  tables/results/TableS4-survival-results-table.xlsx
  tables/results/TableS5-Key-Resources-table.xlsx
Labels: ready for review

#1661 Add Table 1 "Total" row
  tables/output_tables.Rmd
  tables/output_tables.nb.html
  tables/results/Table1-molecular-subtypes.tsv
Labels: revision
